### ISSUE TITLE
Create progress report on website

### ISSUE THREAD

**Issue by markmac99** [markmac99/UKmon-shared#150]
not sure how, but publish a progress report on the website. Perhaps the output of "matchstatus" plus a grep of the nightly log?

**Comment by rickzkm** [comment]
If you like to create it in .md markup, I can then read that file and display on website.

**Comment by markmac99** [comment]
I'll see what i can do :)

**Comment by markmac99** [comment]
Not really relevant now since the process is much quicker and the daily report is sent out within 60 minutes of the batch starting.
