### ISSUE TITLE
ukmonlive doesn't display all cameras

### ISSUE THREAD

**Issue by markmac99** [markmac99/UKmon-shared#249]
Something in ukmon-live is causing certain camera to be dropped, notably Ian Pass' 2nd camera.
Richard tells me the relevant code is
website/live.html
website/assets/js/pages/live.js

This appears to be using the DynamoDB table and possibly MQTT to subscribe to a queue. 
The MQ queue appears to be filtering on files ending in P.jpg. then monitoring when S3 ObjectCreated:Put or ObjectRemoved:Delete messages were sent. 
The Dynamodb code scans the ddb table for items in the right timerange. 
Both functions add to or remove entries from the state.items field using the addItem and removeItem functions
The addItem function drops files containing special characters  then parses the filename to read the date/location/time details.

**Comment by markmac99** [comment]
Fixed one bug - caption not appearing properly on the images
commented out MQTT as its not used
This *may* have fixed the problem with missing cameras, need to check.
Still got the problem that you have to select the camera twice. 

The problem seems to be that the Vue plugin creates a new page when you click the filter button. However the new page is still refreshing at the point that the code tries to read the StationID code again, and so it crashes, causing the page to reload with the default of "All". Pressing Apply again simply resubmits the page, which by now is complete and so tada! it works. 

No idea how to fix it.

**Comment by rickzkm** [comment]
UKMON live will be rebuilt

**Comment by markmac99** [comment]
not within my scope to fix, so closing this ticket
