### ISSUE TITLE
Tweet brightest meteor

### ISSUE THREAD

**Issue by markmac99** [markmac99/UKmon-shared#55]
Tweet the previous night's brightest meteor, provided its reasonably bright. 
Perhaps brightest 2-3 if more than one  may -3 or better.

**Comment by rickzkm** [comment]
I would mark this as a very, very low priority. Manual Tweeting gives us a better choice of text so I would not worry about this too much. If there is no easy way then let's leave it.

**Comment by rickzkm** [comment]
Maybe we can close this one?

**Comment by markmac99** [comment]
With twitter dying i don't propose to progress this, and we can manually tweet images quite easily from ukmon-live or the archive.
