### ISSUE TITLE
Menu doesn't work properly on mobile phone

### ISSUE THREAD

**Issue by markmac99** [markmac99/UKmon-shared#60]
collapses wrongly.

**Comment by markmac99** [comment]
many issues with the menu. I need to start from scratch with a blank example and then introduce the current stylesheets etc until i find out which one is messing it up.

**Comment by rickzkm** [comment]
I am already working on new templates if that's okay.

**Comment by markmac99** [comment]
yep, no problem. For testing i have a dev environment running on my own AWS account, I'd need to work out how you can deploy changes there tho. 
Link to dev envt website is
http://mjmm-ukmonarchive.co.uk.s3-website.eu-west-2.amazonaws.com/reports/index.html

**Comment by markmac99** [comment]
Nobody is complaining and my ajax/bootstrap isn't good enough to figure out why they overlap in certain configs. Closing this ticket.
